version: "3.7"

services:
  web:
    image: bitcoinscala/wallet-server-ui:latest
    user: $BITCOIN_S_UID
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - bitcoin-s-frontend-log:/bitcoin-s
    environment:
      LOG_PATH: "/bitcoin-s/log/"
      BITCOIN_S_HOME: "/bitcoin-s/"
      MEMPOOL_API_URL: "http://mempool.space/api"
      WALLET_SERVER_API_URL: "http://walletserver:9999/"
      WALLET_SERVER_WS: "ws://walletserver:19999/events"
      DEFAULT_UI_PASSWORD: $APP_PASSWORD
      BITCOIN_S_SERVER_RPC_PASSWORD: $APP_PASSWORD
    ports:
      - "3002:3002"
    depends_on:
      - walletserver
  walletserver:
    image: bitcoinscala/bitcoin-s-server:latest
    entrypoint: ["/opt/docker/bin/bitcoin-s-server", "--datadir", "/bitcoin-s", "--conf", "/opt/docker/docker-application.conf"]
    user: $BITCOIN_S_UID
    restart: on-failure
    volumes:
      - bitcoin-s-backend-datadir:/bitcoin-s
    environment:
      BITCOIN_S_NODE_MODE: "neutrino"
      BITCOIN_S_NODE_PEERS: "neutrino.suredbits.com:8333"
      BITCOIN_S_TOR_PROVIDED: "true"
      BITCOIN_S_PROXY_ENABLED: "false"
      BITCOIN_S_TOR_ENABLED: "false"
      BITCOIN_S_DLCNODE_PROXY_ENABLED: "true"
      BITCOIN_S_DLCNODE_TOR_ENABLED: "true"
      BITCOIN_S_DLCNODE_PROXY_SOCKS5: "tor:9050"
      BITCOIN_S_DLCNODE_TOR_CONTROL: "tor:9051"
      BITCOIN_S_DLCNODE_TOR_PASSWORD: "topsecret"
      BITCOIN_S_SERVER_RPC_PASSWORD: $APP_PASSWORD
      DISABLE_JLINK: "1"
    ports:
      - "9999:9999"
    depends_on:
      - tor
  tor:
    image:  bitcoinscala/tor:latest
    entrypoint: ["/tor", "--ExitRelay", "0", "--BridgeRelay",  "0", "--SOCKSPort", "0.0.0.0:9050", "--ControlPort", "0.0.0.0:9051", "--HashedControlPassword", "16:EF3A794FD6F30EF76049147EF252111809E7D51C049FEB353B547C1553"]
    restart: on-failure

volumes:
  bitcoin-s-backend-datadir:
    name: "bitcoin-s-backend-datadir"
    driver: local
    external: false
    driver_opts:
      o: bind
      type: none
      device: ${PWD}/data/wallet
  bitcoin-s-frontend-log:
    name: "bitcoin-s-frontend-log"
    driver: local
    external: false
    driver_opts:
      o: bind
      type: none
      device: ${PWD}/data
