name: Compile & Formatting, Docs, Disabled Secp
env:
  COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}

on:
  pull_request:

jobs:
  compile:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      DISABLE_SECP256K1: "true"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Scala
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'
          cache: 'sbt'
      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
            ~/.bitcoin-s/binaries
          key: ${{ runner.os }}-compile-cache
      - name: Compile and Check Formatting
        run: sbt +test:compile scalafmtCheckAll docs/mdoc cryptoTestJVM/test coreTestJVM/test
