# https://docs.docker.com/ci-cd/github-actions/
name: CI to Docker Hub
on:
  push:
    branches: [master, main, adaptor-dlc, 2021-02-18-github-docker-workflow]
    tags: ["*"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and push
        run: sbt "oracleServer/docker:publish;appServer/docker:publish"
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}